project_id = "ukpejgrghpewwdfztryg"

[functions.faq-chat]
verify_jwt = false

[functions.categorize-transaction]
verify_jwt = false

[functions.subscribe-waitlist]
verify_jwt = false

[functions.unsubscribe-waitlist]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.send-invitation]
verify_jwt = true

[functions.send-deletion-code]
verify_jwt = true

[functions.verify-deletion-code]
verify_jwt = true
