project_id = "ukpejgrghpewwdfztryg"

[functions.faq-chat]
verify_jwt = false

[functions.categorize-transaction]
verify_jwt = false

[functions.subscribe-waitlist]
verify_jwt = false

[functions.unsubscribe-waitlist]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.send-deletion-code]
verify_jwt = false

[functions.verify-deletion-code]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.test-subscription]
verify_jwt = false

[functions.generate-store-images]
verify_jwt = false

[functions.draft-budget]
verify_jwt = false

[functions.create-link-token]
verify_jwt = false

[functions.exchange-plaid-token]
verify_jwt = false
