// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukpejgrghpewwdfztryg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrcGVqZ3JnaHBld3dkZnp0cnlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDg2MjksImV4cCI6MjA3MTYyNDYyOX0.1gSlaPh9Og4xCqrL31RfNw6L2yy6kA0qUpXRNhXML4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});